swagger: "2.0"
info:
  description: "tanyibot api"
  version: 1.0.0
  title: Tanyi Bot open api
  license:
    name: Apache-2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
host: openapi.tanyibot.com
basePath: /apiOpen/v1
tags:
  - name: isv
    description: isv
  - name: tenant
    description: tenant
  - name: phone
    description: phone
schemes:
  - https
paths:
  /isv/updateIsvInfo:
    post:
      tags:
        - isv
      summary: 修改ISV对象的公司签名和回调地址
      description: 修改ISV对象的公司签名和回调地址
      operationId: updateIsvInfo
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: ""
          required: true
          schema:
            $ref: "#/definitions/UpdateIsvInfoReq"
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/APIResponse"
  /isv/genSubAccountIsv:
    post:
      tags:
        - isv
      summary: 通过此接口可生成子账号的ISV账号
      description: 通过此接口可生成子账号的ISV账号
      operationId: genSubAccountIsv
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: ""
          required: true
          schema:
            $ref: "#/definitions/GetSubAccountIsvReq"
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/GetSubAccountIsvResp"
  /isv/getIsvList:
    post:
      tags:
        - isv
      summary: 获取isv列表
      description: 通过此接口获取ISV账号列表
      operationId: getIsvList
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/GetIsvListRsp"
  /tenant/getTenant:
    get:
      tags:
        - tenant
      summary: 获取公司列表接口
      description: 获取公司列表接口
      operationId: getTenant
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/GetTenantRsp"
  /phone/getPhoneList:
    get:
      tags:
        - phone
      summary: 通过接口可以获取所有可用的外呼线路的列表
      description: 通过接口可以获取所有可用的外呼线路的列表
      operationId: getPhoneList
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/GetPhoneListRsp"
  /phone/updatePhoneInfoByTenantPhoneNumberId:
    post:
      tags:
        - phone
      summary: 通过此接口修改线路的归属地、行业、黑名单，只能修改归属客户自己的线路
      description: 通过此接口修改线路的归属地、行业、黑名单，只能修改归属客户自己的线路
      operationId: updatePhoneInfoByTenantPhoneNumberId
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: ""
          required: true
          schema:
            $ref: "#/definitions/UpdatePhoneInfoByTenantPhoneNumberIdReq"
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/APIResponse"
  /phone/updatePhonePriceByTenantPhoneNumberId:
    post:
      tags:
        - phone
      summary: 修改绑定客户线路的价格
      description: 修改绑定客户线路的价格
      operationId: updatePhonePriceByTenantPhoneNumberId
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/APIResponse"
  /csRobot/staffGroupList:
    get:
      tags:
        - csRobot
      summary: 获取人工坐席列表接口
      description: 通过此接口可以获取用户所有的有效坐席组列表信息
      operationId: staffGroupList
      produces:
        - application/json
      parameters:
        - in: query
          name: pageNum
          type: integer
          format: int32
          required: true
        - in: query
          name: pageSize
          type: integer
          format: int32
          required: true
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/StaffGroupListRsp"
  /dialogFlow/getDialogFlowList:
    get:
      summary: 获取公司的机器人话术列表接口
      description: 通过接口可以获取指定公司的所有配置完成的机器人话术
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/DialogFlowList"
definitions:
  DialogFlowList:
    allOf:
      - $ref: "#/definitions/APIResponse"
      - type: object
        properties:
          data:
            type: array
            items:
              $ref: "#/definitions/DialogFlow"
  DialogFlow:
    type: object
    properties:
      dialogFlowId:
        type: integer
        format: int32
        description: 机器人话术id
      name:
        type: string
        description: 机器人话术名称
      industry:
        type: string
        description: 一级行业类型（枚举在枚举说明中）
      subIndustry:
        type: string
        description: 二级行业类型（枚举在枚举说明中）
      intentLevelTagId:
        type: integer
        format: int64
        description: 意向标签分组id
      status:
        type: string
        description: 话术状态(DRAFT 草稿 PENDING_APPROVAL 等待审核 REJECTED 拒绝 APPROVED 审核通过)
      createTime:
        type: string
        description: 创建时间
  StaffGroupListRsp:
    allOf:
      - $ref: "#/definitions/APIResponse"
      - type: object
        properties:
          number:
            type: integer
            format: int32
          pageSize:
            type: integer
            format: int32
          totalElements:
            type: integer
            format: int32
          pages:
            type: integer
            format: int32
          csStaffGroupId:
            type: integer
            format: int64
          groupName:
            type: string
  GetTenantRsp:
    title: GetTenantRsp
    allOf:
      - $ref: "#/definitions/APIResponse"
      - type: object
        properties:
          tenantName:
            type: string
          tenantId:
            type: string
  GetIsvListRsp:
    title: GetIsvListRsp
    allOf:
      - $ref: "#/definitions/APIResponse"
      - type: object
        properties:
          data:
            type: array
            items:
              type: object
              properties:
                tenantSign:
                  type: string
                appKey:
                  type: string
                appSecret:
                  type: string
                callbackUrl:
                  type: string
  UpdateIsvInfoReq:
    title: UpdateIsvInfoReq
    type: object
    required:
      - tenantSign
    properties:
      tenantSign:
        type: string
      callbackUrl:
        type: string
      smsCallbackUrl:
        type: string
  GetSubAccountIsvReq:
    title: GetSubAccountIsvReq
    description: ""
    type: object
    required:
      - tenantSign
      - phoneNumber
    properties:
      tenantSign:
        type: string
      phoneNumber:
        type: string
  GetSubAccountIsvResp:
    title: GetSubAccountIsvResp
    description: ""
    properties:
      code:
        type: integer
        format: int32
        description: 响应码
      requestId:
        type: string
        description: 请求Id
      resultMsg:
        type: string
        description: 响应说明
      tenantSign:
        type: string
        description: 客户签名
      appKey:
        type: string
      appSecret:
        type: string
  GetPhoneListRsp:
    title: GetPhoneListRsp
    description: ""
    allOf:
      - $ref: "#/definitions/APIResponse"
      - type: object
        properties:
          data:
            type: array
            items:
              $ref: "#/definitions/Phone"
  Phone:
    title: Phone
    description: Phone
    type: object
    properties:
      tenantPhoneNumberId:
        type: integer
        format: int64
        description: 电话id
      phoneNumber:
        type: string
        description: 电话号码
      phoneName:
        type: string
        description: 电话号码名称
      phoneType:
        type: string
        description: (MOBILE, "手机"),(LANDLINE, "固话"),(UNFIXED_CALL, "无主叫固话")
      localBillRate:
        type: integer
        format: int32
        description: 本地话费（单位：厘）
      otherBillRate:
        type: integer
        format: int32
        description: 外地话费（单位：厘）
      callOutIndustry:
        type: string
        description: (FINANCE, "金融"),(OTHER, "其他")
      areaCode:
        type: string
        description: 归属地区号
      province:
        type: string
        description: 归属地省
      city:
        type: string
        description: 归属地市
      deadArea:
        type: array
        items:
          properties:
            city:
              type: string
            prov:
              type: string
        description: 无法外呼地区
  UpdatePhoneInfoByTenantPhoneNumberIdReq:
    title: UpdatePhoneInfoByTenantPhoneNumberIdReq
    description: ""
    properties:
      tenantPhoneNumberId:
        type: int
        format: int64
        description: 线路id
        allowEmptyValue: false
        example: 1010
      areaCode:
        type: string
        description: 线路归属地
        example: http://www.baidu.com
      province:
        type: string
        description: 线路归属地省
        example: 浙江
      city:
        type: string
        description: 线路归属地市
        example: 杭州
      callOutIndustry:
        type: string
        enum:
          - FINANCE
          - OTHER
        description: (FINANCE, "金融"),(OTHER, "其他")
      deadArea:
        type: object
        description: 线路黑名单地址
        properties:
          city:
            type: string
          prov:
            type: string
  BaseReq:
    title: BaseReq
    description: ""
    properties:
      appKey:
        type: string
      appSecret:
        type: string
      tenantSign:
        type: string
      version:
        type: string
      timestamp:
        type: string
      signature:
        type: string
  APIResponse:
    title: APIResponse
    description: ""
    properties:
      code:
        type: integer
        format: int32
        description: 响应码
      requestId:
        type: string
        description: 请求id
      resultMsg:
        type: string
        description: 响应说明
